# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
}

terraform {
  backend "s3" {}
  required_providers {
    aws = {
      source  = "registry.terraform.io/hashicorp/aws"
      version = "3.59.0"
    }
  }
  required_version = ">=1.0.7"
}
